CREATE TABLE users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    USERPASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    DATE_ENRGISET DATE DEFAULT(CURRENT_DATE)
)ENGINE INNODB;
CREATE TABLE contact (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(150),
    ADDERS VARCHAR(255),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
)ENGINE INNODB;
